ANAL_DIR=anal
ASM_DIR=asm

all:
	make -C $(ANAL_DIR) all
	make -C $(ASM_DIR) all

install:
	make -C $(ANAL_DIR) install
	make -C $(ASM_DIR) install

uninstall:
	make -C $(ANAL_DIR) uninstall
	make -C $(ASM_DIR) uninstall

clean:
	make -C $(ANAL_DIR) clean
	make -C $(ASM_DIR) clean
