ARCHS=

ARCHS+=ba2.mk
ARCHS+=x86_bea.mk
ARCHS+=arm_v35.mk
#ARCHS+=x86_im.mk
ARCHS+=x86_simple.mk
ARCHS+=x86_udis.mk
ARCHS+=m68k_net.mk
ARCHS+=evm.mk
ARCHS+=atombios.mk
ARCHS+=nios.mk

include ../../plugs.mk
