PWD=$(shell pwd)
VERSION=@VERSION@
DESTDIR=
PREFIX=@PREFIX@
HOST_OS=@HOST_OS@
LIBDIR=@LIBDIR@
INSTALL_LIB=@INSTALL_LIB@

#LIBYARA_CFLAGS=@LIBYARA_CFLAGS@
#LIBYARA_LDFLAGS=@LIBYARA_LDFLAGS@
LIBYARA_CFLAGS=
LIBYARA_LDFLAGS=-lyara
R2_CFLAGS=@R2_CFLAGS@
R2_LDFLAGS=@R2_LDFLAGS@
YR_CFLAGS=@YR_CFLAGS@
YR_LDFLAGS=@YR_LDFLAGS@

CFLAGS+=${R2_CFLAGS} ${LIBYARA_CFLAGS} ${YR_CFLAGS}
LDFLAGS+=${R2_LDFLAGS} ${LIBYARA_LDFLAGS} ${YR_LDFLAGS}
CFLAGS+=-I. -fPIC
LDFLAGS+=-shared

ifneq ("$(wildcard ../../options.mk)","")
include ../../options.mk
endif

MOD=core_yara3

THEDIR=$(DESTDIR)/$(LIBDIR)/radare2-extras/$(VERSION)/

all: $(MOD).$(EXT_SO)

$(MOD).$(EXT_SO): ${MOD}.o
	${CC} ${MOD}.o ${CFLAGS} ${LDFLAGS} -o ${MOD}.${EXT_SO}

clean:
	rm -f ${MOD}.o ${MOD}.${EXT_SO}

mrproper: clean
	rm -f Makefile

install:
	mkdir -p ${DESTDIR}${LIBDIR}/radare2-extras/${VERSION}/
	cd ${DESTDIR}${LIBDIR}/radare2-extras/ ; ln -fs ${VERSION} last
	${INSTALL_LIB} ${MOD}.${EXT_SO} $(THEDIR)/${MOD}.${EXT_SO}
	cd ${THEDIR} ; ln -fs ${VERSION} last
	rm -rf $(THEDIR)/yara
	mkdir -p $(THEDIR)/yara
	cp -f ../rules-yara3/* $(THEDIR)/rules-yara3

symstall:
	mkdir -p $(THEDIR)
	ln -fs ${PWD}/${MOD}.${EXT_SO} $(THEDIR)/$(MOD).$(EXT_SO)
	cd ${THEDIR} ; ln -fs ${VERSION} last
	rm -rf $(THEDIR)/yara
	ln -fs $(PWD)/../rules-yara3 $(THEDIR)/rules-yara3

uninstall:
	rm -f ${THEDIR}/$(MOD).$(EXT_SO)
