bea:
	cd p ; $(MAKE) asm_x86_bea.$(LIBEXT)

msil:
	cd p ; $(MAKE) asm_msil.$(LIBEXT)

tab:
	cd p ; $(MAKE) asm_x86_tab.$(LIBEXT)

m68k:
	cd p ; $(MAKE) asm_m68k.$(LIBEXT)
	
clean:
	rm -f p/asm_x86_bea.$(LIBEXT)
	rm -f p/asm_x86_tab.$(LIBEXT)
	rm -f p/asm_m68k.$(LIBEXT)

include ../../options.mk
