#!/bin/sh
CWD=$(dirname $0)
OLD=$PWD
cd $CWD
if [ ! -d venv ]; then
    python -m venv venv
fi
. venv/bin/activate
if [ ! -x venv/bin/angr ]; then
    pip install angr
    pip install capstone==5.0.3
fi
cd $OLD
angr $@
