#!/bin/sh
if [ -z "$R2_FILE" ]; then
    echo "Run this script from radare2. with !r2angr ([sailr,phenox,dream])"
    exit 1
fi
if [ "$R2_BADDR" = 0 ]; then
    echo "If the function is not found use r2 -B 0x400000"
elif [ "${R2_OFFSET:-0}" -lt 10000 ]; then
    echo "If the function is not found use r2 -B 0x400000"
fi
ARG=""
[ -n "$1" ] && ARG="--structurer $1"
[ -z "$TMPDIR" ] && TMPDIR=/tmp
angr decompile $ARG --functions=${R2_XOFFSET} \
    ${R2_FILE} 2>"${TMPDIR}/.r2angr.txt" ||
    echo "r2pm -ci angr, Check ${TMPDIR}/.r2angr.txt for details"
