PWD=$(shell pwd)
VERSION=@VERSION@
DESTDIR=
PREFIX=@PREFIX@
HOST_OS=@HOST_OS@
LIBDIR=@LIBDIR@
INSTALL_LIB=@INSTALL_LIB@

#LIBYARA_CFLAGS=@LIBYARA_CFLAGS@
#LIBYARA_LDFLAGS=@LIBYARA_LDFLAGS@
LIBYARA_CFLAGS=
LIBYARA_LDFLAGS=-lyara
R2_CFLAGS=@R2_CFLAGS@
R2_LDFLAGS=@R2_LDFLAGS@

CFLAGS+=${R2_CFLAGS} ${LIBYARA_CFLAGS}
LDFLAGS+=${R2_LDFLAGS} ${LIBYARA_LDFLAGS}
CFLAGS+=-I. -fPIC
LDFLAGS+=-shared

include ../../options.mk

MOD=core_yara2

THEDIR=$(DESTDIR)/$(LIBDIR)/radare2-extras/$(VERSION)/

all: $(MOD).$(EXT_SO)

$(MOD).$(EXT_SO): ${MOD}.o
	${CC} ${CFLAGS} ${LDFLAGS} ${MOD}.o -o ${MOD}.${EXT_SO}

clean:
	rm -f ${MOD}.o ${MOD}.${EXT_SO}

mrproper: clean
	rm -f Makefile

install:
	mkdir -p ${DESTDIR}${LIBDIR}/radare2-extras/${VERSION}/
	${INSTALL_LIB} ${MOD}.${EXT_SO} $(THEDIR)/${MOD}.${EXT_SO}
	cd ${THEDIR} ; ln -fs ${VERSION} last
	rm -rf $(THEDIR)/yara
	mkdir -p $(THEDIR)/yara
	cp -f ../files/* $(THEDIR)/yara

symstall:
	mkdir -p $(THEDIR)
	ln -fs ${PWD}/${MOD}.${EXT_SO} $(THEDIR)/$(MOD).$(EXT_SO)
	cd ${THEDIR} ; ln -fs ${VERSION} last
	rm -rf $(THEDIR)/yara
	ln -fs $(PWD)/../yara $(THEDIR)/yara

uninstall:
	rm -f ${THEDIR}/$(MOD).$(EXT_SO)
