PWD=$(shell pwd)
VERSION=@VERSION@
DESTDIR=
PREFIX=@PREFIX@
HOST_OS=@HOST_OS@
LIBDIR=@LIBDIR@
INSTALL_LIB=@INSTALL_LIB@

#LIBYARA_CFLAGS=@LIBYARA_CFLAGS@
#LIBYARA_LDFLAGS=@LIBYARA_LDFLAGS@
LIBYARA_CFLAGS=
LIBYARA_LDFLAGS=-lyara
R2_CFLAGS=@R2_CFLAGS@
R2_LDFLAGS=@R2_LDFLAGS@

CFLAGS+=${R2_CFLAGS} ${LIBYARA_CFLAGS}
LDFLAGS+=${R2_LDFLAGS} ${LIBYARA_LDFLAGS}
CFLAGS+=-I. -fPIC
LDFLAGS+=-shared

ifneq ("$(wildcard ../../options.mk)","")
include ../../options.mk
endif

MOD=core_yara2

THEDIR=$(DESTDIR)/$(LIBDIR)/radare2-extras/$(VERSION)/

all: $(MOD).$(LIBEXT)

$(MOD).$(LIBEXT): ${MOD}.o
	${CC} ${CFLAGS} ${LDFLAGS} ${MOD}.o -o ${MOD}.${LIBEXT}

clean:
	rm -f ${MOD}.o ${MOD}.${LIBEXT}

mrproper: clean
	rm -f Makefile

install:
	mkdir -p ${DESTDIR}${LIBDIR}/radare2-extras/${VERSION}/
	${INSTALL_LIB} ${MOD}.${LIBEXT} $(THEDIR)/${MOD}.${LIBEXT}
	cp -f ${THEDIR}/${MOD}.${LIBEXT} ${R2PM_PLUGDIR}/${MOD}.${LIBEXT}
	cd ${THEDIR} ; ln -fs ${VERSION} ../last
	rm -rf ${R2PM_PLUGDIR}/yara
	mkdir -p ${R2PM_PLUGDIR}/yara
	cp -rf ../rules-yara2/ ${R2PM_PLUGDIR}/

symstall:
	mkdir -p $(THEDIR)
	ln -fs ${PWD}/${MOD}.${LIBEXT} $(THEDIR)/$(MOD).$(LIBEXT)
	cd ${THEDIR} ; ln -fs ${VERSION} last
	rm -rf $(THEDIR)/yara
	ln -fs $(PWD)/../rules-yara2 $(THEDIR)/rules-yara2

uninstall:
	rm -f ${R2PM_PLUGDIR}/${MOD}.${LIBEXT}
	rm -rf ${R2PM_PLUGDIR}/rules-yara2
	rm -rf ${R2PM_PLUGDIR}/yara
