ARCHS=

ARCHS+=x86_udis.mk
ARCHS+=spc700.mk
ARCHS+=ba2.mk
ARCHS+=x86_olly.mk
ARCHS+=x86_tab.mk
ARCHS+=arm_v35.mk
ARCHS+=armthumb.mk 
ARCHS+=ppc_disasm.mk
ARCHS+=psosvm.mk
ARCHS+=m68k_net.mk
ARCHS+=blackfin.mk
ARCHS+=x86_bea.mk
ARCHS+=msil.mk
ARCHS+=nios.mk
ARCHS+=swf.mk
ARCHS+=vc4.mk
ARCHS+=mc6809.mk
ARCHS+=z80_nc.mk
ARCHS+=x86_zyan.mk
ARCHS+=evm.mk
ARCHS+=atombios.mk


include ../../plugs.mk

