ARCHS=

ARCHS+=agc.mk
ARCHS+=armthumb.mk 
ARCHS+=ppc_disasm.mk
ARCHS+=psosvm.mk
ARCHS+=m68k.mk
ARCHS+=blackfin.mk
ARCHS+=x86_bea.mk
ARCHS+=msil.mk
ARCHS+=swf.mk
ARCHS+=vc4.mk

include ../../plugs.mk

