PWD=$(shell pwd)
R2VERSION=@R2VERSION@
DESTDIR=
PREFIX=@PREFIX@
HOST_OS=@HOST_OS@
LIBDIR=@LIBDIR@
INSTALL_LIB=@INSTALL_LIB@

#LIBYARA_CFLAGS=@LIBYARA_CFLAGS@
#LIBYARA_LDFLAGS=@LIBYARA_LDFLAGS@
LIBYARA_CFLAGS=
LIBYARA_LDFLAGS=-lyara
R2_CFLAGS=@R2_CFLAGS@
R2_LDFLAGS=@R2_LDFLAGS@
YR_CFLAGS=@YR_CFLAGS@
YR_LDFLAGS=@YR_LDFLAGS@

CFLAGS+=${R2_CFLAGS} ${LIBYARA_CFLAGS} ${YR_CFLAGS}
LDFLAGS+=${R2_LDFLAGS} ${LIBYARA_LDFLAGS} ${YR_LDFLAGS}
CFLAGS+=-I. -fPIC
LDFLAGS+=-shared

ifneq ("$(wildcard ../../options.mk)","")
include ../../options.mk
endif

MOD=core_yara

all: $(MOD).$(LIBEXT)

$(MOD).$(LIBEXT): ${MOD}.o
	${CC} ${MOD}.o ${CFLAGS} ${LDFLAGS} -o ${MOD}.${LIBEXT}

clean:
	rm -f ${MOD}.o ${MOD}.${LIBEXT}

mrproper: clean
	rm -f Makefile

install:
	${INSTALL_LIB} ${MOD}.${LIBEXT} $(R2PM_PLUGDIR)/${MOD}.${LIBEXT}
	rm -rf $(R2PM_PLUGDIR)/yara
	mkdir -p $(R2PM_PLUGDIR)/yara
	cp -rf ../rules-yara3/ $(R2PM_PLUGDIR)/

symstall:
	ln -fs ${PWD}/${MOD}.${LIBEXT} $(R2PM_PLUGDIR)/$(MOD).$(LIBEXT)
	rm -rf $(R2PM_PLUGDIR)/yara
	ln -fs $(PWD)/../rules-yara3 $(R2PM_PLUGDIR)/rules-yara3

uninstall:
	rm -f ${R2PM_PLUGDIR}/$(MOD).$(LIBEXT)
	rm -rf ${R2PM_PLUGDIR}/rules-yara3
	rm -rf ${R2PM_PLUGDIR}/yara
