PWD=$(shell pwd)
VERSION=@VERSION@
DESTDIR=
PREFIX=@PREFIX@
HOST_OS=@HOST_OS@
LIBDIR=@LIBDIR@
INSTALL_LIB=@INSTALL_LIB@

R2PM_USRPLUGIN_DIR=$(shell r2 -H R2_USER_PLUGINS)
LIBEXT=$(shell r2 -H R2_LIBEXT)
#LIBYARA_CFLAGS=@LIBYARA_CFLAGS@
#LIBYARA_LDFLAGS=@LIBYARA_LDFLAGS@
LIBYARA_CFLAGS=
LIBYARA_LDFLAGS=-lyara
R2_CFLAGS=@R2_CFLAGS@
R2_LDFLAGS=@R2_LDFLAGS@
YR_CFLAGS=@YR_CFLAGS@
YR_LDFLAGS=@YR_LDFLAGS@

CFLAGS+=${R2_CFLAGS} ${LIBYARA_CFLAGS} ${YR_CFLAGS}
LDFLAGS+=${R2_LDFLAGS} ${LIBYARA_LDFLAGS} ${YR_LDFLAGS}
CFLAGS+=-I. -fPIC
LDFLAGS+=-shared
CFLAGS+=-DR2Y_VERSION=\"$(VERSION)\"

ifneq ($(wildcard ../../options.mk),)
include ../../options.mk
endif

MOD=core_yara

all: $(MOD).$(LIBEXT)

$(MOD).$(LIBEXT): ${MOD}.o
	$(CC) -g ${MOD}.o ${CFLAGS} ${LDFLAGS} -o ${MOD}.${LIBEXT}

clean:
	rm -f ${MOD}.o ${MOD}.${LIBEXT}

mrproper: clean
	rm -f Makefile

RULESDIR=$(R2PM_USRPLUGIN_DIR)/rules-yara3

user-install install:
	${INSTALL_LIB} ${MOD}.${LIBEXT} $(R2PM_USRPLUGIN_DIR)/${MOD}.${LIBEXT}
	mkdir -p $(RULESDIR)
	cp -rf *.gz $(RULESDIR)

symstall:
	ln -fs ${PWD}/${MOD}.${LIBEXT} $(R2PM_USRPLUGIN_DIR)/$(MOD).$(LIBEXT)
	rm -rf $(R2PM_USRPLUGIN_DIR)/yara
	mkdir -p $(RULESDIR)
	for a in *.gz ; do ln -fs $(PWD)/$$a $(RULESDIR)/$$a ; done

user-uninstall uninstall:
	rm -f ${R2PM_USRPLUGIN_DIR}/$(MOD).$(LIBEXT)
	rm -rf $(RULESDIR)
	rm -rf ${R2PM_USRPLUGIN_DIR}/yara
