#!/bin/sh
TARGET="$1"

if [ -z "$1" ]; then
	TARGET="${R2_FILE}"
fi
if [ -z "$TARGET" ]; then
	echo "Usage: r2 -i '.!r2snow'" > /dev/stderr
	exit 1
fi
if [ -f "$1" ]; then
	echo "Cannot find $1" > /dev/stderr
	exit 1
fi

nocode --print-cxx=r2snow-source.c --print-ranges=r2snow-addrof.txt $TARGET
r2snow.pl
exit 0
