#!/bin/sh
TARGET="$1"
R2SNOW_PATH=/tmp

if [ -z "$1" ]; then
	TARGET="${R2_FILE}"
fi
if [ -z "$TARGET" ]; then
	echo "Usage: r2 -i '.!r2snow'" > /dev/stderr
	exit 1
fi
if [ -f "$1" ]; then
	echo "Cannot find $1" > /dev/stderr
	exit 1
fi

$R2SNOW_PATH/r2snow.bin $TARGET > /dev/null
$R2SNOW_PATH/r2snow.pl

