name: CI

on:
  push:
  
  pull_request:


jobs:

  build-extras:
    name: Build radare2 extras and r2pipe
    runs-on: ubuntu-22.04
    env:
      EXTERNAL_BUILDS: 'keystone-lib unicorn-lib'
      LOCAL_BUILDS: 'asahi blackfin blessr2 keystone r2svd vc4 x86iced'
      TESTS: 'keystone vc4'
    steps:
    - uses: actions/checkout@v3
      with:
        repository: radareorg/radare2
        ref: master
        path: ./radare2
    - uses: radareorg/github-actions@v3
      with:
        from-git: true
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        path: ./radare2-extras
    - name: Init r2pm
      run: r2pm -U
    - name: Compile and install plugins
      run: |
        set -e
        for p in $EXTERNAL_BUILDS ; do
          echo $p
          r2pm -i $p
        done
        R2PM_GITDIR="$(r2pm -H R2PM_GITDIR)"
        for p in $LOCAL_BUILDS ; do
          echo $p
          ln -s "$GITHUB_WORKSPACE/radare2-extras" "$R2PM_GITDIR/$p"
          R2PM_OFFLINE=1 r2pm -i $p
        done
    - name: Test plugins
      working-directory: radare2/test
      run: |
        set -e
        for p in $TESTS ; do
          echo $p
          make $p
        done
        set +e
